# Generated by Django 3.0.6 on 2020-05-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('vendor', 'model', 'year')},
        ),
    ]
